#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Xandros15\Tumbler\Console\Download;

require_once __DIR__ . '/vendor/autoload.php';

$container = require __DIR__ . '/dependencies.php';
const APP_NAME = 'Tumbler';
const APP_VER = '2.1.0';

$command = new Download($container);

$app = new Application(APP_NAME, APP_VER);
$app->add($command);
$app->setDefaultCommand($command->getName(), true);

$exitCode = $app->run();

exit($exitCode);
